### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Nowaker** [encharm/http-master#112]
Number of exceptions: 11
Time span: October 27th through today
Seen on: 0.12.7

```
Nov 03 14:32:02 apps.stratushost.eu node[15619]: [7] [Uncaught exception] TypeError: undefined is not a function
Nov 03 14:32:02 apps.stratushost.eu node[15619]: at Object.RedirectMiddleware.requestHandler [as middleware] (/usr/lib/node_modules/http-master/modules/middleware/redirect.js:15:11)
Nov 03 14:32:02 apps.stratushost.eu node[15619]: at DispatchTable.requestHandler (/usr/lib/node_modules/http-master/modules/middleware/router.js:87:20)
Nov 03 14:32:02 apps.stratushost.eu node[15619]: at DispatchTable.dispatchRequest (/usr/lib/node_modules/http-master/src/DispatchTable.js:216:17)
Nov 03 14:32:02 apps.stratushost.eu node[15619]: at runMiddleware (/usr/lib/node_modules/http-master/modules/middleware/router.js:13:25)
Nov 03 14:32:02 apps.stratushost.eu node[15619]: at /usr/lib/node_modules/http-master/modules/middleware/router.js:18:13
Nov 03 14:32:02 apps.stratushost.eu node[15619]: at logger (/usr/lib/node_modules/http-master/node_modules/morgan/index.js:144:5)
Nov 03 14:32:02 apps.stratushost.eu node[15619]: at Object.LogMiddleware.requestHandler [as middleware] (/usr/lib/node_modules/http-master/modules/middleware/log.js:6:7)
Nov 03 14:32:02 apps.stratushost.eu node[15619]: at runMiddleware (/usr/lib/node_modules/http-master/modules/middleware/router.js:13:25)
Nov 03 14:32:02 apps.stratushost.eu node[15619]: at Object.middleware (/usr/lib/node_modules/http-master/modules/middleware/router.js:24:7)
Nov 03 14:32:02 apps.stratushost.eu node[15619]: at Object.RouterMiddleware.requestHandler (/usr/lib/node_modules/http-master/modules/middleware/router.js:98:14)
Nov 03 14:32:02 apps.stratushost.eu node[15619]: Worker 7 failed with code 1/null ... starting replacement
Nov 03 14:32:02 apps.stratushost.eu node[15619]: Worker 30 started in place of worker 7
```

**Comment by Nowaker** [comment]
Number of exceptions: 68
Time span: 22 days
